---
- name: Deploy nginx website on Ubuntu 20.04 EC2 Instance
  hosts: localhost
  become: true
  tasks: 
    - name: Install nginx
      apt: 
        name: nginx
        update_cache: yes
    - name: Create default index page
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "Hello from Ty"
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
